on:
  github:
    branches:
      only: main
defaults:
  resources:
    instance-type: C4
jobs:
  CloneRepo:
    resources:
      instance-type: C4
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: context.event.github.url
      ref: context.event.github.ref
  TrainModel:
    env:
      PS_MODEL_PATH: /my-trained-model
      max_steps: "100"
      train_epochs: "100"
    resources:
      instance-type: P4000
    needs:
      - CloneRepo
    inputs:
      repo: CloneRepo.outputs.repo
    outputs:
      trained-model:
        type: dataset
        with:
          ref: gradient-next/mnist-sample
    uses: container@v1
    with:
      args:
        - bash
        - "-c"
        - cd /inputs/repo && python mnist.py && cp -R /my-trained-model /outputs/trained-model
      image: "tensorflow/tensorflow:1.13.1-gpu-py3"
  UploadModel:
    needs:
      - TrainModel
    inputs:
      model: TrainModel.outputs.trained-model
    outputs:
      model-id:
        type: string
    uses: create-model@v1
    with:
      name: my-trained-model
      type: Tensorflow #Tensorflow, ONNX, or Custom
  DeployModel:
    needs:
      - UploadModel
    uses: script@v1
    with:
      script: |
        cat > ./deployment.yaml <<EOF
        image: lucone83/streamlit-nginx
        port: 8080
        env:
          - name: ENV
            value: VAR
        resources:
          replicas: 1
          instanceType: C4
        EOF
        gradient deployments update --id "7cf5482c-71a1-42ce-ad9c-0bf5a61e4ff6" --spec ./deployment.yaml
      image: paperspace/gradient-sdk
